name: Common.Logging - Build and Deploy Nuget

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: 'Common.Email.csproj'
      PROJECT_PATH: 'src/Common.Email'
      PROJECT_NAME_TESTS: 'Common.Email.Tests.csproj'
      PROJECT_PATH_TESTS: 'src/Common.Email.Test'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}

      - name: Build
        run: >
          dotnet build ${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}
          --configuration Release
          --no-restore

      - name: Restore Test dependencies
        run: dotnet restore ${{ env.PROJECT_PATH_TESTS }}/${{ env.PROJECT_NAME_TESTS }}

      - name: Test
        run: dotnet test ${{ env.PROJECT_PATH_TESTS }}/${{ env.PROJECT_NAME_TESTS }}

      - name: Pack
        run: >
          dotnet pack ${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}
          --configuration Release
          --no-build
          --include-symbols
          --output out
          --include-source

      - name: Publish Nuget to GitHub Packages
        run: >
          dotnet nuget push "out/*.nupkg"
          --api-key ${{ secrets.NUGET_PAT}}
          --source https://nuget.pkg.github.com/AlephTechHouse/index.json
